# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  api:
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    volumes:
      - "./api:/$WORKDIR"
      - "~/.ssh:/root/.ssh"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      FRONT_DOMAIN: "http://localhost:$FRONT_PORT"
      API_DOMAIN: "http://localhost:$API_PORT"
      SSH_KEY_PATH: "$SSH_KEY_PATH"
      EDITOR: vim
    ports:
      - "$API_PORT:$CONTAINER_PORT"
    depends_on:
      - db
    # Docker環境でbinding.pryを使用できるようにする
    tty: true
    stdin_open: true

  front:
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
    volumes:
      - "./front:/$WORKDIR"
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - '8025:8025'
