version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  aws-s3: circleci/aws-s3@3.0.0

commands:
  npm_install:
    steps:
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "~/read_aloud_checker/front/package.json" }}
        working_directory: ~/read_aloud_checker/front
    - run:
        name: install-packages
        command: npm install
        working_directory: ~/read_aloud_checker/front
    - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "~/read_aloud_checker/front/package.json" }}
        working_directory: ~/read_aloud_checker/front

jobs:
  build_api:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          BUNDLER_VERSION: 2.3.7
    working_directory: ~/read_aloud_checker/api
    steps:
      - checkout:
          path: ~/read_aloud_checker
      - ruby/install-deps

  test_api:
    docker:
      - image: cimg/ruby:3.1.2
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: mysqlpassword
          MYSQL_DATABASE: app_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
      TZ: Asia/Tokyo
    working_directory: ~/read_aloud_checker/api
    steps:
      - checkout:
          path: ~/read_aloud_checker
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rspec

  lint_api:
    docker:
      - image: cimg/ruby:3.1.2
    working_directory: ~/read_aloud_checker/api
    steps:
      - checkout:
          path: ~/read_aloud_checker
      - ruby/install-deps
      - run:
          name: rubocop
          command: bundle exec rubocop

  deploy_api:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          BUNDLER_VERSION: 2.3.7
    working_directory: ~/read_aloud_checker/api
    steps:
      - checkout:
          path: ~/read_aloud_checker
      - ruby/install-deps
      - add_ssh_keys:
          fingerprints: "2c:45:bf:7a:4f:87:e7:b5:81:cd:2e:4f:ae:53:cb:79"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy

  test_front:
    docker:
      - image: cimg/node:16.16.0
    working_directory: ~/read_aloud_checker/front
    steps:
      - checkout:
          path: ~/read_aloud_checker
      - npm_install
      - run:
          name: test
          command: npm run test
          working_directory: ~/read_aloud_checker/front

  deploy_front:
    docker:
      - image: cimg/node:16.16.0
      - image: cimg/python:3.6
    working_directory: ~/read_aloud_checker/front
    steps:
      - checkout:
          path: ~/read_aloud_checker
      - npm_install
      - run:
          name: build
          command: VITE_API_DOMAIN=$VITE_API_DOMAIN VITE_CLOUD_FRONT=$VITE_CLOUD_FRONT VITE_GA4_ID=$VITE_GA4_ID npm run build
      - aws-s3/sync:
          from: dist
          to: "s3://${AWS_TARGET_BUCKET}"

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_api
      - test_api:
          requires:
            - build_api
      - lint_api:
          requires:
            - build_api
      - deploy_api:
          requires:
            - test_api
          filters:
            branches:
              only: main
      - test_front
      - deploy_front:
          requires:
            - test_front
          filters:
            branches:
              only: main
