inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "tmp/**/*"
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
  NewCops: enable

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# 1_000_000 と区切り文字が 2 個以上必要になる場合のみ _ 区切りを必須にする
Style/NumericLiterals:
  MinDigits: 7

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/NestedParenthesizedCalls:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 150
  Exclude:
    - "spec/**/*"

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ReturnFromStub:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Exclude:
    - "spec/**/*"
